Rename hyperparameter tuning to refine the model
carpentries-incubator/deep-learning-intro pull request #380
Opened 2023-08-16 12:40 UTC by svenvanderburg

Fixes #270

2023-08-16 12:41 UTC, svenvanderburg commented on episodes/2-keras.Rmd
> +Note that the outcome you have might be slightly different from what is shown in this tutorial.
I spotted that this was in the wrong place, this is better I think.

2023-11-01 13:12 UTC, dsmits requested changes
one small remark

2023-11-01 13:12 UTC, dsmits commented on episodes/2-keras.Rmd
> +many hyper parameter and model architecture choices.
```suggestion
many hyperparameter and model architecture choices.
```

2023-11-01 13:13 UTC, dsmits approved these changes

2023-11-01 13:30 UTC, merged