Add comparison to feedforward neural network episode 4
carpentries-incubator/deep-learning-intro pull request #421
Opened 2023-09-27 13:49 UTC by svenvanderburg

Fixes #363

2023-09-27 13:50 UTC, svenvanderburg commented
@NidhiGowdra does this address the idea you raised in #303 ?

2023-09-29 08:51 UTC, psteinb requested changes
small working improvement

2023-09-29 08:51 UTC, psteinb commented on episodes/4-advanced-layer-types.Rmd
> +You can choice how much you want to go in depth here, probably depending on time. You have several options:
```suggestion
Depending on time, the following discussion can be extended in depth up to your liking. You have several options:
```

2023-10-04 06:31 UTC, svenvanderburg commented on episodes/4-advanced-layer-types.Rmd
> +You can choice how much you want to go in depth here, probably depending on time. You have several options:
Much better!

2023-10-04 06:34 UTC, merged

2023-10-10 00:47 UTC, NidhiGowdra commented
Hello @svenvanderburg, the second round went well, smooth delivery, good feedback and most of the issues previously raised have now been resolved. Appreciate the improvements and suggestions you provided to improve content delivery :)

2023-10-11 11:21 UTC, svenvanderburg commented
Hi @NidhiGowdra that is great to hear! Please keep raising issues if you encounter any problems :)